server:
  port: 8091

spring:
  application:
    name: app

tracing:
  url: http://192.168.1.33:4318/v1/traces

metrics:
  url: http://192.168.1.33:4318/v1/metrics

logs:
  url: http://192.168.1.33:4318/v1/logs

management:
  endpoints:
    web:
      exposure:
        include: [ prometheus, "*" ]
        exclude:
    jmx:
      exposure:
        include: "*"
  metrics:
    tags:
      application: app-metrics-rch

    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
  endpoint:
    metrics:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      enabled: true
# autoconfiguration
  otlp:
    metrics:
      export:
        url: ${OTLP_URL_LOCAL}:${OTLP_PORT}/v1/metrics
        enabled: true
    tracing:
      endpoint: ${OTLP_URL_LOCAL}:${OTLP_PORT}/v1/traces
    logs:
      endpoint: ${OTLP_URL}:${OTLP_PORT}/v1/logs
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p
#    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p

io.opentelemetry.level: FINE
